/* Write your PL/SQL query statement below */
SELECT NAME, COALESCE(SUM(DISTANCE),0) AS TRAVELLED_DISTANCE FROM USERS U, RIDES R 
   WHERE U.ID = R.USER_ID(+) GROUP BY U.id, U.name ORDER BY TRAVELLED_DISTANCE DESC, NAME ASC;